export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
